'use client'

import React, { useRef, useState } from 'react'
import { motion, AnimatePresence, useInView } from 'framer-motion'

const tabs = [
  { id: 'notes', label: 'Apple Notes' },
  { id: 'imessage', label: 'iMessage' },
  { id: 'meme', label: 'Meme Ad' },
  { id: 'table', label: 'Comparison Table' },
]

const examples: Record<string, React.ReactNode> = {
  notes: (
    <div className="bg-yellow-50 rounded-2xl p-6 font-mono text-sm max-w-lg mx-auto border border-yellow-100 shadow-sm">
      <div className="flex items-center gap-2 mb-4">
        <div className="w-3 h-3 rounded-full bg-yellow-400" />
        <div className="w-3 h-3 rounded-full bg-yellow-300" />
        <div className="w-3 h-3 rounded-full bg-yellow-200" />
        <span className="ml-2 text-xs text-yellow-600 font-sans font-medium">Notes — Private</span>
      </div>
      <p className="text-gray-800 font-bold text-base mb-4 font-sans leading-snug">
        Why I canceled Ahrefs after 4 years and switched to their competitor 📊
      </p>
      <ul className="space-y-2 text-gray-700 leading-relaxed">
        <li>• Was paying $199/mo for features I used maybe 20% of</li>
        <li>• Their domain rating system penalizes new sites artificially</li>
        <li>• Found a tool that shows <strong>actual traffic potential</strong>, not vanity scores</li>
        <li>• Rank tracker updates daily (Ahrefs is every 7 days on base plan)</li>
        <li>• Went from page 4 to page 1 on 3 keywords in 6 weeks after switching</li>
        <li>• Costs $79/mo. I'm not going back.</li>
        <li>• DM me "SEO" and I'll send you the comparison I used to decide</li>
      </ul>
      <div className="mt-4 pt-4 border-t border-yellow-200 text-xs text-gray-400 font-sans">
        Angle A — Problem-First · Format 01 · Generated by MediaBrain
      </div>
    </div>
  ),

  imessage: (
    <div className="bg-gray-50 rounded-2xl p-6 max-w-lg mx-auto border border-gray-100 shadow-sm">
      <div className="flex items-center gap-2 mb-6 pb-4 border-b border-gray-200">
        <div className="w-8 h-8 rounded-full bg-blue-500 flex items-center justify-center text-white text-xs font-bold">K</div>
        <div>
          <p className="font-semibold text-gray-900 text-sm">Kofi</p>
          <p className="text-xs text-gray-400">iMessage</p>
        </div>
      </div>
      <div className="space-y-3 text-sm">
        <div className="flex justify-start">
          <div className="bg-gray-200 text-gray-800 rounded-2xl rounded-tl-sm px-4 py-2.5 max-w-[78%]">
            bro my SEO is dead, been trying to rank for 8 months, nothing
          </div>
        </div>
        <div className="flex justify-end">
          <div className="bg-blue-500 text-white rounded-2xl rounded-tr-sm px-4 py-2.5 max-w-[78%]">
            are you still chasing DR scores or actual traffic potential
          </div>
        </div>
        <div className="flex justify-start">
          <div className="bg-gray-200 text-gray-800 rounded-2xl rounded-tl-sm px-4 py-2.5 max-w-[78%]">
            what's the difference?
          </div>
        </div>
        <div className="flex justify-end">
          <div className="bg-blue-500 text-white rounded-2xl rounded-tr-sm px-4 py-2.5 max-w-[78%]">
            DR is a made-up metric. traffic potential is what actually gets you clients
          </div>
        </div>
        <div className="flex justify-start">
          <div className="bg-gray-200 text-gray-800 rounded-2xl rounded-tl-sm px-4 py-2.5 max-w-[78%]">
            ok how do I see traffic potential
          </div>
        </div>
        <div className="flex justify-end">
          <div className="bg-blue-500 text-white rounded-2xl rounded-tr-sm px-4 py-2.5 max-w-[78%]">
            I switched from the big name tool to this one called [Product]. showing me keywords the other tool marked as "hard" that I'm now ranking for
          </div>
        </div>
        <div className="flex justify-start">
          <div className="bg-gray-200 text-gray-800 rounded-2xl rounded-tl-sm px-4 py-2.5 max-w-[78%]">
            send me the link
          </div>
        </div>
      </div>
      <div className="mt-4 pt-4 border-t border-gray-200 text-xs text-gray-400">
        Angle D — Competitor-Contrast · Format 02 · Generated by MediaBrain
      </div>
    </div>
  ),

  meme: (
    <div className="max-w-lg mx-auto space-y-3">
      <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden">
        <div className="p-4 border-b border-gray-100">
          <p className="text-sm text-gray-700 font-medium">Still checking your domain rating every morning like it means something</p>
        </div>

        {/* Drake meme mockup */}
        <div className="grid grid-cols-2 divide-x divide-gray-100">
          <div className="p-6 flex flex-col items-center gap-3">
            <div className="text-4xl">😒</div>
            <p className="text-center text-sm font-bold text-gray-800 uppercase tracking-wide leading-tight">
              Domain Rating score: 34
            </p>
          </div>
          <div className="p-6 flex flex-col items-center gap-3 bg-red-50">
            <div className="text-4xl">👉</div>
            <p className="text-center text-sm font-bold text-red-700 uppercase tracking-wide leading-tight">
              Traffic potential: 12,400/mo
            </p>
          </div>
        </div>

        <div className="p-4 bg-gray-50 border-t border-gray-100">
          <p className="text-xs text-gray-500 italic">Template: Drake Pointing · Image spec provided to designer</p>
        </div>
      </div>

      <div className="text-xs text-gray-400 text-center">
        Angle C — Credibility-First · Format 03 · Generated by MediaBrain
      </div>
    </div>
  ),

  table: (
    <div className="max-w-2xl mx-auto">
      <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden">
        <div className="p-6 border-b border-gray-100">
          <h3 className="font-bold text-black text-lg leading-snug">
            If you're still using Ahrefs because it's "the industry standard," read this.
          </h3>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-gray-100 bg-gray-50">
                <th className="text-left p-4 font-semibold text-gray-700">Feature</th>
                <th className="text-center p-4 font-semibold text-red-700 bg-red-50">Our Tool</th>
                <th className="text-center p-4 font-semibold text-gray-500">DIY / Google</th>
                <th className="text-center p-4 font-semibold text-gray-500">Ahrefs</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-50">
              {[
                ['Traffic potential view', '✅ Real-time', '❌ Guesswork', '⚠️ Estimated'],
                ['Rank tracker updates', '✅ Daily', '❌ Manual', '⚠️ Weekly (base)'],
                ['New site friendly', '✅ Yes', '❌ Slow start', '❌ DR bias'],
                ['Content gap analysis', '✅ Built-in', '❌ None', '✅ Yes'],
                ['Learning curve', '✅ 30 min', '❌ Months', '⚠️ Steep'],
                ['Price / outcome', '✅ $79/mo', '⚠️ Your time', '❌ $199/mo+'],
              ].map(([feature, ours, diy, competitor]) => (
                <tr key={feature} className="hover:bg-gray-50 transition-colors">
                  <td className="p-4 text-gray-700 font-medium">{feature}</td>
                  <td className="p-4 text-center font-medium text-gray-800 bg-red-50/50">{ours}</td>
                  <td className="p-4 text-center text-gray-500">{diy}</td>
                  <td className="p-4 text-center text-gray-500">{competitor}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        <div className="p-6 border-t border-gray-100 bg-gray-50 text-center">
          <p className="text-sm font-semibold text-gray-800">Try free for 14 days — no credit card →</p>
        </div>
      </div>
      <div className="text-xs text-gray-400 text-center mt-3">
        Angle B — Outcome-First · Format 04 · Generated by MediaBrain
      </div>
    </div>
  ),
}

export default function OutputExamples() {
  const ref = useRef<HTMLDivElement>(null)
  const isInView = useInView(ref, { once: true, amount: 0.15 })
  const [activeTab, setActiveTab] = useState('notes')

  return (
    <section id="output-examples" ref={ref} className="py-24 bg-white">
      <div className="max-w-7xl mx-auto px-6">

        {/* Header */}
        <motion.div
          className="text-center mb-14"
          initial={{ opacity: 0, y: 30 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.7 }}
        >
          <p className="text-red-600 font-semibold text-sm uppercase tracking-widest mb-4">Real Output</p>
          <h2 className="text-4xl md:text-5xl font-bold text-black mb-6 relative inline-block">
            What MediaBrain Produces
            <motion.div
              className="absolute -bottom-3 left-0 h-1 bg-red-600"
              initial={{ width: 0 }}
              animate={isInView ? { width: '100%' } : {}}
              transition={{ duration: 1, delay: 0.5 }}
            />
          </h2>
          <p className="text-xl text-gray-600 max-w-2xl mx-auto mt-6">
            Example output from running MediaBrain on an SEO tool's landing page. Zero human edits.
          </p>
        </motion.div>

        {/* Tabs */}
        <motion.div
          className="flex flex-wrap justify-center gap-2 mb-10"
          initial={{ opacity: 0, y: 20 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.5, delay: 0.3 }}
        >
          {tabs.map((tab) => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={`px-5 py-2.5 rounded-full text-sm font-medium transition-all duration-200 ${
                activeTab === tab.id
                  ? 'bg-black text-white shadow-md'
                  : 'bg-gray-100 text-gray-600 hover:bg-gray-200'
              }`}
            >
              {tab.label}
            </button>
          ))}
        </motion.div>

        {/* Content */}
        <AnimatePresence mode="wait">
          <motion.div
            key={activeTab}
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -16 }}
            transition={{ duration: 0.3 }}
          >
            {examples[activeTab]}
          </motion.div>
        </AnimatePresence>

        <motion.p
          className="text-center text-sm text-gray-400 mt-8"
          initial={{ opacity: 0 }}
          animate={isInView ? { opacity: 1 } : {}}
          transition={{ delay: 0.8 }}
        >
          These are 4 of 16 creatives. Each of the 4 angles gets all 4 formats.
        </motion.p>
      </div>
    </section>
  )
}
